### ISSUE TITLE
Student Select / Change Seating

### ISSUE THREAD

**Issue by jsmith** [SWE-4103-Group-3/Project#43]
A student should be able chose their seat for each course. This seat will persist until the student decides to change their seat or the course is deleted.

This issue was created from #11 

- [x] Add check for instructors so that they can't choose a seat

**Comment by jacsmith21** [comment]
Sweet! This is going to be fun

**Comment by brandon1024** [comment]
@jacsmith21 How is the progress on this issue? How are you tackling linking a student to a seat? The reason I ask is because in my issue [here](https://github.com/SWE-4103-Group-3/Project/issues/5), I'm creating an action to clear student seating. I might hold off on my issue until yours get merged :)

**Comment by jsmith** [comment]
That makes sense. Right now we've just added a student object to the seat object! Clearing would just involve removing that student object from the seat.

We'll hopefully finish this issue within the next few days!
