### ISSUE TITLE
Instructors Clear a Seating Plan

### ISSUE THREAD

**Issue by dsteen338** [SWE-4103-Group-3/Project#5]
As an instructor, I need to be able to clear a seating plan so that I can use it again for the next delivery of my class.

At any time during the duration of a course, (ie any time through my fall semester) I want to be able to press a button and clear the seating plan (i.e. back to a blank n*n grid of the size that it was before I cleared it). 

The most recent structure of the seating plan should be able to persist if you want it to.

For instance: Year 1, template with 4 seats, year 2, template with 5 seats, If I would like to set up a seating plan for Year 3, I can pick the 5 seat template from year 2, but the data from year 1 is lost, as it only stores the most recent (This applies to if you change templates halfway through a semester or something as well)

**Comment by brandon1024** [comment]
@mwalz1 Can I have some clarification from PO? What are the exact tasks involved with this issue? Is it as simple as adding a `clear` button in the course view to reset the grid back to the n * m grid for a given course?

**Comment by mwalz1** [comment]
@brandon1024 What I propose is two clear buttons.  One to clear the names of students.  Another to set all grid squares back to the default green.

This would allow the instructor to a) keep the grid layout and simply clear the students.  Or b) reset the grid to the default green n*m grid and then press another button to clear the names.

This could be useful to have two separate buttons in the event that it is midway through a term and the professor decides to change the layout, but does not want to remove all the student's names.  it would be easier for the professor to set the grid to default green, rather than manually change every single square.

Will reach out to Dr. MacIsaac and let you know what she wants exactly.

**Comment by mwalz1** [comment]
@brandon1024 An update to this issue:
No need to maintain most recent seating plan any more, as every time this class is offered, a new course will be created all together.
